// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/domain (interfaces: CheckinRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/checkin_repository.go -package mock_domain . CheckinRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCheckinRepository is a mock of CheckinRepository interface.
type MockCheckinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckinRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckinRepositoryMockRecorder is the mock recorder for MockCheckinRepository.
type MockCheckinRepositoryMockRecorder struct {
	mock *MockCheckinRepository
}

// NewMockCheckinRepository creates a new mock instance.
func NewMockCheckinRepository(ctrl *gomock.Controller) *MockCheckinRepository {
	mock := &MockCheckinRepository{ctrl: ctrl}
	mock.recorder = &MockCheckinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckinRepository) EXPECT() *MockCheckinRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckinRepository) Create(ctx context.Context, c *domain.Checkin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckinRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckinRepository)(nil).Create), ctx, c)
}

// FindTodayByUserAndEstablishment mocks base method.
func (m *MockCheckinRepository) FindTodayByUserAndEstablishment(ctx context.Context, userID, establishmentID string) (*domain.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTodayByUserAndEstablishment", ctx, userID, establishmentID)
	ret0, _ := ret[0].(*domain.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTodayByUserAndEstablishment indicates an expected call of FindTodayByUserAndEstablishment.
func (mr *MockCheckinRepositoryMockRecorder) FindTodayByUserAndEstablishment(ctx, userID, establishmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTodayByUserAndEstablishment", reflect.TypeOf((*MockCheckinRepository)(nil).FindTodayByUserAndEstablishment), ctx, userID, establishmentID)
}

// ListByUser mocks base method.
func (m *MockCheckinRepository) ListByUser(ctx context.Context, userID string) ([]domain.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockCheckinRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockCheckinRepository)(nil).ListByUser), ctx, userID)
}
