// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/domain (interfaces: EstablishmentRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/establishment_repository.go -package mock_domain . EstablishmentRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEstablishmentRepository is a mock of EstablishmentRepository interface.
type MockEstablishmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEstablishmentRepositoryMockRecorder
	isgomock struct{}
}

// MockEstablishmentRepositoryMockRecorder is the mock recorder for MockEstablishmentRepository.
type MockEstablishmentRepositoryMockRecorder struct {
	mock *MockEstablishmentRepository
}

// NewMockEstablishmentRepository creates a new mock instance.
func NewMockEstablishmentRepository(ctrl *gomock.Controller) *MockEstablishmentRepository {
	mock := &MockEstablishmentRepository{ctrl: ctrl}
	mock.recorder = &MockEstablishmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEstablishmentRepository) EXPECT() *MockEstablishmentRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockEstablishmentRepository) List(ctx context.Context) ([]*domain.Establishment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Establishment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEstablishmentRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEstablishmentRepository)(nil).List), ctx)
}
