// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/domain (interfaces: HighlightRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/highlight_repository.go -package mock_domain . HighlightRepository
//

package mock_domain

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockHighlightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHighlightRepositoryMockRecorder
	isgomock struct{}
}

type MockHighlightRepositoryMockRecorder struct {
	mock *MockHighlightRepository
}

func NewMockHighlightRepository(ctrl *gomock.Controller) *MockHighlightRepository {
	mock := &MockHighlightRepository{ctrl: ctrl}
	mock.recorder = &MockHighlightRepositoryMockRecorder{mock}
	return mock
}

func (m *MockHighlightRepository) EXPECT() *MockHighlightRepositoryMockRecorder {
	return m.recorder
}

func (m *MockHighlightRepository) Create(ctx context.Context, highlight *domain.Highlight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, highlight)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockHighlightRepositoryMockRecorder) Create(ctx, highlight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHighlightRepository)(nil).Create), ctx, highlight)
}

func (m *MockHighlightRepository) Delete(ctx context.Context, establishmentID, reviewID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, establishmentID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockHighlightRepositoryMockRecorder) Delete(ctx, establishmentID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHighlightRepository)(nil).Delete), ctx, establishmentID, reviewID)
}

func (m *MockHighlightRepository) Exists(ctx context.Context, establishmentID, reviewID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, establishmentID, reviewID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockHighlightRepositoryMockRecorder) Exists(ctx, establishmentID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockHighlightRepository)(nil).Exists), ctx, establishmentID, reviewID)
}

func (m *MockHighlightRepository) CountByEstablishment(ctx context.Context, establishmentID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByEstablishment", ctx, establishmentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockHighlightRepositoryMockRecorder) CountByEstablishment(ctx, establishmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByEstablishment", reflect.TypeOf((*MockHighlightRepository)(nil).CountByEstablishment), ctx, establishmentID)
}

func (m *MockHighlightRepository) ListByEstablishment(ctx context.Context, establishmentID string) ([]domain.Highlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEstablishment", ctx, establishmentID)
	ret0, _ := ret[0].([]domain.Highlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockHighlightRepositoryMockRecorder) ListByEstablishment(ctx, establishmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEstablishment", reflect.TypeOf((*MockHighlightRepository)(nil).ListByEstablishment), ctx, establishmentID)
}
