// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/domain (interfaces: ReviewLikeRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/review_like_repository.go -package mock_domain . ReviewLikeRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReviewLikeRepository is a mock of ReviewLikeRepository interface.
type MockReviewLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewLikeRepositoryMockRecorder is the mock recorder for MockReviewLikeRepository.
type MockReviewLikeRepositoryMockRecorder struct {
	mock *MockReviewLikeRepository
}

// NewMockReviewLikeRepository creates a new mock instance.
func NewMockReviewLikeRepository(ctrl *gomock.Controller) *MockReviewLikeRepository {
	mock := &MockReviewLikeRepository{ctrl: ctrl}
	mock.recorder = &MockReviewLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewLikeRepository) EXPECT() *MockReviewLikeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewLikeRepository) Create(ctx context.Context, like *domain.ReviewLike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewLikeRepositoryMockRecorder) Create(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewLikeRepository)(nil).Create), ctx, like)
}

// Delete mocks base method.
func (m *MockReviewLikeRepository) Delete(ctx context.Context, userID, reviewID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewLikeRepositoryMockRecorder) Delete(ctx, userID, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewLikeRepository)(nil).Delete), ctx, userID, reviewID)
}
