// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/domain (interfaces: ReviewRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_domain/review_repository.go -package mock_domain . ReviewRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewRepository) Create(ctx context.Context, review *domain.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewRepositoryMockRecorder) Create(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepository)(nil).Create), ctx, review)
}

// GetByID mocks base method.
func (m *MockReviewRepository) GetByID(ctx context.Context, reviewID string) (*domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, reviewID)
	ret0, _ := ret[0].(*domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReviewRepositoryMockRecorder) GetByID(ctx, reviewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReviewRepository)(nil).GetByID), ctx, reviewID)
}

// GetByCheckinID mocks base method.
func (m *MockReviewRepository) GetByCheckinID(ctx context.Context, checkinID string) (*domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCheckinID", ctx, checkinID)
	ret0, _ := ret[0].(*domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCheckinID indicates an expected call of GetByCheckinID.
func (mr *MockReviewRepositoryMockRecorder) GetByCheckinID(ctx, checkinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCheckinID", reflect.TypeOf((*MockReviewRepository)(nil).GetByCheckinID), ctx, checkinID)
}

// ListByEstablishment mocks base method.
func (m *MockReviewRepository) ListByEstablishment(ctx context.Context, establishmentID string, options domain.ReviewListOptions) ([]domain.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEstablishment", ctx, establishmentID, options)
	ret0, _ := ret[0].([]domain.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEstablishment indicates an expected call of ListByEstablishment.
func (mr *MockReviewRepositoryMockRecorder) ListByEstablishment(ctx, establishmentID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEstablishment", reflect.TypeOf((*MockReviewRepository)(nil).ListByEstablishment), ctx, establishmentID, options)
}
