// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/application/usecases (interfaces: ListEstablishmentsUseCase)
//
// Generated by this command:
//
//	mockgen -destination mock_usecases/list_establishments.go -package mock_usecases . ListEstablishmentsUseCase
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockListEstablishmentsUseCase is a mock of ListEstablishmentsUseCase interface.
type MockListEstablishmentsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListEstablishmentsUseCaseMockRecorder
	isgomock struct{}
}

// MockListEstablishmentsUseCaseMockRecorder is the mock recorder for MockListEstablishmentsUseCase.
type MockListEstablishmentsUseCaseMockRecorder struct {
	mock *MockListEstablishmentsUseCase
}

// NewMockListEstablishmentsUseCase creates a new mock instance.
func NewMockListEstablishmentsUseCase(ctrl *gomock.Controller) *MockListEstablishmentsUseCase {
	mock := &MockListEstablishmentsUseCase{ctrl: ctrl}
	mock.recorder = &MockListEstablishmentsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListEstablishmentsUseCase) EXPECT() *MockListEstablishmentsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListEstablishmentsUseCase) Execute(ctx context.Context) ([]domain.Establishment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]domain.Establishment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListEstablishmentsUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListEstablishmentsUseCase)(nil).Execute), ctx)
}
