// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/application/usecases (interfaces: LoginUserUseCase)
//
// Generated by this command:
//
//	mockgen -destination mock_usecases/login_user.go -package mock_usecases . LoginUserUseCase
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUserUseCase is a mock of LoginUserUseCase interface.
type MockLoginUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserUseCaseMockRecorder
	isgomock struct{}
}

// MockLoginUserUseCaseMockRecorder is the mock recorder for MockLoginUserUseCase.
type MockLoginUserUseCaseMockRecorder struct {
	mock *MockLoginUserUseCase
}

// NewMockLoginUserUseCase creates a new mock instance.
func NewMockLoginUserUseCase(ctrl *gomock.Controller) *MockLoginUserUseCase {
	mock := &MockLoginUserUseCase{ctrl: ctrl}
	mock.recorder = &MockLoginUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserUseCase) EXPECT() *MockLoginUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUserUseCase) Execute(ctx context.Context, input domain.UserCredentials) (*domain.AuthenticationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain.AuthenticationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUserUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUserUseCase)(nil).Execute), ctx, input)
}
