// Code generated by MockGen. DO NOT EDIT.
// Source: fivestars/internal/application/usecases (interfaces: RegisterUserUseCase)
//
// Generated by this command:
//
//	mockgen -destination mock_usecases/register_user.go -package mock_usecases . RegisterUserUseCase
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	domain "fivestars/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegisterUserUseCase is a mock of RegisterUserUseCase interface.
type MockRegisterUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUserUseCaseMockRecorder
	isgomock struct{}
}

// MockRegisterUserUseCaseMockRecorder is the mock recorder for MockRegisterUserUseCase.
type MockRegisterUserUseCaseMockRecorder struct {
	mock *MockRegisterUserUseCase
}

// NewMockRegisterUserUseCase creates a new mock instance.
func NewMockRegisterUserUseCase(ctrl *gomock.Controller) *MockRegisterUserUseCase {
	mock := &MockRegisterUserUseCase{ctrl: ctrl}
	mock.recorder = &MockRegisterUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUserUseCase) EXPECT() *MockRegisterUserUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterUserUseCase) Execute(ctx context.Context, inputLogin domain.UserRegistration) (*domain.AuthenticationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, inputLogin)
	ret0, _ := ret[0].(*domain.AuthenticationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterUserUseCaseMockRecorder) Execute(ctx, inputLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterUserUseCase)(nil).Execute), ctx, inputLogin)
}
